server.port=9082

management.endpoint.health.show-details=never

resilience4j.ratelimiter.instances.productService.limit-for-period=10
resilience4j.ratelimiter.instances.productService.limit-refresh-period=10s
resilience4j.ratelimiter.instances.productService.timeout-duration=0
